version: "3.8"
services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    #Here we specify healthcheck operation (what command executes to test, number of times, interval and starting time)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      retries: 2
      start_period: 20s
      timeout: 10s
    networks:
      trello:
        #Here we set host name that other services will use
        aliases:
          - "database"

  discovery-service:
    container_name: discovery-service
    build:
      context: discovery-service
      dockerfile: Dockerfile
    image: discovery-service:latest
    ports:
      - "8761:8761"
    healthcheck:
      #Send request to this url only once and behave like a web spider (not download pages).
      #Exit 1 ensures exit code 1 on failure.
      #No-verbose means that in case of error it will be printed
      test: wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1
      interval: 20s
      retries: 2
      start_period: 20s
      timeout: 10s
    networks:
      - trello

  config-service:
    container_name: config-service
    build:
      context: config-service
      dockerfile: Dockerfile
    image: config-service:latest
    ports:
      - "8888:8888"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health
      interval: 20s
      retries: 2
      start_period: 20s
      timeout: 10s
    networks:
      - trello
    depends_on:
      discovery-service:
        condition: service_healthy

  #Here we configure our main task service
  task-service:
    #Here we specify container name
    container_name: task-service
    #Here we describe which dockerfile and where it located (context field) use to build image of this service
    build:
      context: task-service
      dockerfile: Dockerfile
    #Here we specify name of the image
    image: task-service:latest
    #Here we specify ports ---
    ports:
      - "8080:8080"
    #Here we say what services should be running to this service (task-service) to be able to run
    depends_on:
      postgres-db:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    #Here we say what network this service should use
    networks:
      - trello


#Here we define network and it's name
networks:
  trello:
    driver: bridge